[package]
name = "arwain_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
pbjson = "0.5.1"
prost = "0.11.5"
serde = "1.0.152"
tonic = "0.8.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
