#!/bin/bash
script_dir=$(cd $(dirname $0); pwd)
root_dir=$(cd $script_dir/..; pwd)
cd $root_dir

if ! type brew > /dev/null 2>&1; then
  echo "WARNING: I don't have a way to automatically install dependencies. So instead, I'll just report when a dependency is missing." 1>&2
fi

require_tool() {
    local tool=$1
    local installable=$2
    if type $1 > /dev/null 2>&1; then
        return
    elif type brew > /dev/null 2>&1; then
        brew install $2
    else
        echo "WARNING: Missing dependency: $1" 1>&2
    fi
}

require_tool "buf" "bufbuild/buf/buf"

if ! type rustup > /dev/null 2>&1; then
    echo "WARNING: Missing dependency: rustup" 1>&2
    echo "WARNING: You can install rustup from https://rustup.rs/" 1>&2
    exit 1
fi

if ! type cargo > /dev/null 2>&1; then
    echo "WARNING: Missing dependency: cargo" 1>&2
    echo "WARNING: Use rustup to configure cargo" 1>&2
    exit 1
fi