[package]
name = "arwaind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
tonic = "0.8.3"
arwain_proto = { path = "../arwain_proto" }